apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-dados
  labels:
    type: mysql-dados
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: /volumes/mysql-B
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
---
apiVersion: v1
kind: Service
metadata:
  name: database-svc
spec:
  selector:
    app: mysql-database
  ports:
  - port: 3306
    targetPort: 3306
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: backend-src
spec:
  selector:
    app: php-backend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30000
  type: NodePort
